### ISSUE TITLE
#3 问题没有解决，往下偏移的距离更大了。

### ISSUE THREAD

**Issue by junixapp** [fluttercandies/w_popup_menu#4]

**Comment by wanglu1209** [comment]
老铁，加我微信 17610912320
前几天没看到，不好意思

**Comment by junixapp** [comment]
我用overlay实现了，项目着急。

**Comment by wanglu1209** [comment]
前几天模拟了一下你那边的UI，确实发现了一些问题，
本以为能解决掉你那边的问题，没想到还是有bug。
这样吧，如果有时间的话，能否加一下微信，详细说一下你那边的布局，
或者等你那边有时间，给我提供一下思路，你觉得到底是哪里出了问题，我这边好改正。
